# Generated by Django 5.0.6 on 2024-06-07 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_tutor', models.CharField(max_length=100)),
                ('data_nascimento', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nome_do_animal', models.CharField(max_length=100)),
                ('tipo_de_animal', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Hamster', 'Hasmster'), ('Coelho', 'Coelho'), ('Outro', 'Outro')], max_length=50)),
                ('idade_do_animal', models.CharField(max_length=50)),
                ('peso_do_animal', models.CharField(max_length=50)),
                ('observacoes', models.TextField()),
                ('tipo_de_agendamento', models.CharField(choices=[('Consulta', 'Consulta'), ('Exames', 'Exames'), ('Vacinação', 'Vacinação'), ('Cirurgia', 'Cirurgia')], default='Consulta', max_length=20)),
                ('data', models.DateField(blank=True, default=None, null=True)),
                ('horario', models.TimeField(choices=[(datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00')])),
            ],
        ),
    ]
