# Generated by Django 5.0.6 on 2024-06-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_de_agendamento',
            field=models.CharField(choices=[(None, 'Selecione'), ('Consulta', 'Consulta'), ('Exames', 'Exames'), ('Vacinação', 'Vacinação'), ('Cirurgia', 'Cirurgia')], default='Consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo_de_animal',
            field=models.CharField(choices=[(None, 'Selecione'), ('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Hamster', 'Hasmster'), ('Coelho', 'Coelho'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
