# Generated by Django 5.0.6 on 2024-06-13 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_agendamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_de_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 13, 19, 11, 191242, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
